// <auto-generated />
using System;
using System.Reflection;
using System.Resources;
using System.Runtime.InteropServices;

// General Information about an assembly is controlled through the following 
// set of attributes. Change these attribute values to modify the information
// associated with an assembly.
[assembly: AssemblyTitle("EricForce.BinaryHeap")]
[assembly: AssemblyDescription("An implementation of the binary heap algorithm.")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("Eric Force")]
[assembly: AssemblyProduct("BinaryHeap")]
[assembly: AssemblyCopyright("Copyright © Eric Force 2017")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]
[assembly: NeutralResourcesLanguage("en")]
[assembly: ComVisible(false)]
[assembly: Guid("E4BB2A53-A4F1-4535-AF43-3DD3F15E410A")]

// Version information for an assembly consists of the following four values:
//
//      Major Version
//      Minor Version 
//      Build Number
//      Revision
//
// You can specify all the values or you can default the Build and Revision Numbers 
// by using the '*' as shown below:
// [assembly: AssemblyVersion("1.0.*")]
[assembly: AssemblyVersion("1.0.0.0")]
[assembly: AssemblyFileVersion("1.0.0.0")]
[assembly: CLSCompliant(true)]